version: 2

updates:
  # Update GitHub Actions versions in workflows
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: all
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "CI: "
      include: "scope"
